name: CPU CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v4
      - name: Install
        run: uv pip install --system -e ".[dev]"
      - name: PyCompile
        run: python -m py_compile $(find reliquary_inference tests -name '*.py' -print)
      - name: Pytest
        run: pytest -q
